### ISSUE TITLE
Wayfinder 1.0 - Game crashes back to main screen while trying to load a save or starting a new game. It's NOT A MMO!

### ISSUE THREAD

**Issue by namesmine** [Detanup01/gbe_fork#67]
After the game was updated to 1.0 yesterday, any iteration of GBE stopped working with it. 
The game goes as far as trying to start or load a save, but then goes back to "Press any key" (which is the default behavior of the game if Steam isn't running, I tested with CSF).

I tried all possible GBE combinations, it's as if the GBE isn't there at all.

**Comment by Detanup01** [comment]
Can you post the game logs?

**Comment by namesmine** [comment]
Sure, here are the last 2 logs I have from failed attempts:

[Atlas.log](https://github.com/user-attachments/files/17483286/Atlas.log)
[Atlas_2.log](https://github.com/user-attachments/files/17483288/Atlas_2.log)

**Comment by Detanup01** [comment]
Seems like the game trying to auth you in some 3rd party server and thats why not working.

**Comment by namesmine** [comment]
It's trying to auth into the EOS server that they added without telling anyone. 
Even with a modified EOS dll, GBE's steam dll just sets the game on a loop, and other options aren't unlocking any extra content. Is there a way to fix this situation?

**Comment by Detanup01** [comment]
Write a server emulator.
Other than that, no. 
High chance Nemirs old emu not gonna work, the game still probably trying to access some sort of server (check with mitmproxy/wireshark or whatever proxy you want to sniff it).
Also has EAC. Yeah.
This game is not a game, its a Service model.
Sorry

**Comment by namesmine** [comment]
Wow, you did NOT even bother to look at the game, and closed this before I even answered. I'm not hooked on the net 24/7.

This game USED to be a MMO, that's why you see leftover files from it. It turned into a single player with co-op. 
As I said, before version 1.0, the emu hooked fine (the EOS dll has been there since the crossplay was implemented, on v 0.7). After 1.0, the emu stopped hooking to the game.

This isn't an MMO anymore, we can play the game offline and before 1.0, the emu connected fine and I was playing with friends.

**Comment by Detanup01** [comment]
I did look at the LOGS you provided and NOT the game.

Logs said:
EOS: EOS_Connect_ExternalTokenValidationFailed cannot decrypt ticket. (Primary reason it failed)
Which means you used gc false and new_token false in ini.
Also you did not generate achievements, and branches.

You sent logs are UNREAL LOGS and not STEAM EMULATOR LOGS.
Can see some stuff but not everything.
And as I read their ToS/Eula you didn't need to read like 20 pages in the forst they declare as a service.

Either you fix what the logs said then maybe can play or play older version (since you said its playable).

I did not gonna purchase this game and download 60gb for nothing.
Check newest release and generate the app related stuff properly!
And use Nemirs epic emu, might still works if not then you can no longer play.
